plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://machina-ratiocinatrix.github.io
baseurl: /command

title: Command
description: Command and response.

machine:
  name: Machina-Ratiocinatrix
  verb: think
  command:
  server: https://localhost:443

app:
  worker_name: localhostapi.js

lm:
  model: gpt-5.2
  max_output_tokens: 100000
  reasoning_effort: high
  reasoning_summary: detailed
  temperature: 1.0

github_settings:
  owner: machina-ratiocinatrix
  repo: machina_ratiocinatrix
  file_name: machina.yaml
  branch: main
  token_file: github.txt
